// react-app/src/components/Navbar.jsx
import React, { useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import useAuth from '../hooks/useAuth';
import axios from 'axios';

const Navbar = () => {
  const { user, token, logout } = useAuth();
  const navigate = useNavigate();
  const [unreadCount, setUnreadCount] = useState(0);

  useEffect(() => {
    if (user && token) {
      axios.get('http://localhost:5000/api/notify/unread-count', {
        headers: { Authorization: `Bearer ${token}` }
      }).then(res => setUnreadCount(res.data.count))
        .catch(() => {});
    }
  }, [user, token]);

  const handleLogout = () => {
    logout();
    navigate('/login');
  };

  return (
    <nav style={{ background: 'var(--primary)', color: 'white', display: 'flex', justifyContent: 'space-between', padding: '0 20px', alignItems: 'center', height: '60px' }}>
      <h2 style={{ margin: 0 }}>Alumni Connect</h2>
      {user && (
        <div style={{ display: 'flex', gap: '15px', alignItems: 'center' }}>
          <Link to="/dashboard" style={{ color: 'white', textDecoration: 'none' }}>Dashboard</Link>
          <Link to="/directory" style={{ color: 'white', textDecoration: 'none' }}>Directory</Link>
          <Link to="/opportunities" style={{ color: 'white', textDecoration: 'none' }}>Opportunities</Link>
          
          <Link to="/notifications" style={{ color: 'white', textDecoration: 'none' }}>
            Notifications {unreadCount > 0 && <span style={{ background: 'red', borderRadius: '50%', padding: '2px 6px', fontSize: '12px' }}>{unreadCount}</span>}
          </Link>
          <Link to="/networking" style={{ color: 'white', textDecoration: 'none' }}>
            Networking
          </Link>

          {user.role === 'alumni' && (
            <>
              <Link to="/my-listings" style={{ color: 'white', textDecoration: 'none' }}>My Listings</Link>
              <Link to="/post-job" style={{ color: 'white', textDecoration: 'none' }}>Post Job</Link>
            </>
          )}

          {user.role === 'student' && (
            <Link to="/my-applications" style={{ color: 'white', textDecoration: 'none' }}>My Applications</Link>
          )}

          {user.role === 'admin' && (
            <Link to="/admin" style={{ color: 'white', textDecoration: 'none' }}>Admin Panel</Link>
          )}

          <button onClick={handleLogout} className="btn-secondary" style={{ padding: '4px 10px' }}>Logout</button>
        </div>
      )}
    </nav>
  );
};

export default Navbar;

// angular-app/src/app/navbar/navbar.component.ts
import { Component, OnInit } from '@angular/core';
import { RouterLink } from '@angular/router';
import { NotificationService } from '../services/notification.service';
import { AuthService } from '../services/auth.service';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [RouterLink, CommonModule],
  templateUrl: './navbar.component.html'
})
export class NavbarComponent implements OnInit {
  unreadCount = 0;
  userRole: string | null = null;
  reactBase = 'http://localhost:5173';

  constructor(
    private notificationService: NotificationService,
    private auth: AuthService
  ) {}

  ngOnInit() {
    this.notificationService.unreadCount$.subscribe(count => {
      this.unreadCount = count;
    });
    this.notificationService.loadUnreadCount();

    // Decode role from JWT so we can show/hide role-specific nav links
    const token = this.auth.getToken();
    if (token) {
      try {
        const payload = JSON.parse(atob(token.split('.')[1]));
        this.userRole = payload.role;
      } catch { this.userRole = null; }
    }
  }
}

<nav style="background: var(--primary); color: white; display: flex; justify-content: space-between; padding: 0 20px; align-items: center; height: 60px;">
  <h2 style="margin: 0;">Alumni Connect</h2>

  <div style="display: flex; gap: 15px; align-items: center; flex-wrap: wrap;">
    <!-- Links that always go back to React app -->
    <a [href]="reactBase + '/dashboard'" style="color: white; text-decoration: none;">Dashboard</a>
    <a [href]="reactBase + '/directory'" style="color: white; text-decoration: none;">Directory</a>
    <a [href]="reactBase + '/opportunities'" style="color: white; text-decoration: none;">Opportunities</a>

    <!-- Angular internal links -->
    <a routerLink="/connections" style="color: white; text-decoration: none;">Networking</a>
    <a routerLink="/notifications" style="color: white; text-decoration: none;">
      Notifications
      <span *ngIf="unreadCount > 0"
        style="background: red; border-radius: 50%; padding: 2px 6px; font-size: 12px; margin-left: 4px;">
        {{ unreadCount }}
      </span>
    </a>

    <!-- Alumni only -->
    <ng-container *ngIf="userRole === 'alumni'">
      <a [href]="reactBase + '/my-listings'" style="color: white; text-decoration: none;">My Listings</a>
      <a [href]="reactBase + '/post-job'" style="color: white; text-decoration: none;">Post Job</a>
    </ng-container>

    <!-- Student only -->
    <a *ngIf="userRole === 'student'"
       [href]="reactBase + '/my-applications'"
       style="color: white; text-decoration: none;">My Applications</a>

    <!-- Admin only -->
    <a *ngIf="userRole === 'admin'"
       [href]="reactBase + '/admin'"
       style="color: white; text-decoration: none;">Admin Panel</a>

    <!-- Logout goes back to React login -->
    <a [href]="reactBase + '/login'"
       style="color: white; text-decoration: none; border: 1px solid white; padding: 4px 10px; border-radius: 4px;">
      Logout
    </a>
  </div>
</nav>
