// angular-app/src/app/notifications/notifications.component.ts
import { Component, OnInit } from '@angular/core';
import { NotificationService } from '../services/notification.service';
import { CommonModule, DatePipe } from '@angular/common';

@Component({
  selector: 'app-notifications',
  standalone: true,
  imports: [CommonModule, DatePipe],
  templateUrl: './notifications.component.html'
})
export class NotificationsComponent implements OnInit {
  notifications: any[] = [];
  unreadCount$ = this.notificationService.unreadCount$;

  constructor(private notificationService: NotificationService) {}

  ngOnInit() {
    this.fetchNotifications();
    this.notificationService.loadUnreadCount();
  }

  fetchNotifications() {
    this.notificationService.getNotifications().subscribe(res => {
      this.notifications = res;
    });
  }

  markAllRead() {
    this.notificationService.markAllRead().subscribe(() => {
      this.fetchNotifications();
      this.notificationService.loadUnreadCount();
    });
  }

  markAsRead(id: string, currentlyRead: boolean) {
    if (currentlyRead) return;
    this.notificationService.markRead(id).subscribe(() => {
      this.fetchNotifications();
      this.notificationService.loadUnreadCount();
    });
  }
}

<div>
  <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 20px;">
    <h2>Notifications</h2>
    <div *ngIf="(unreadCount$ | async) as count">
      <button *ngIf="count > 0" class="btn-primary" (click)="markAllRead()">Mark All Read ({{ count }})</button>
    </div>
  </div>

  <div *ngIf="notifications.length === 0" style="color: var(--text-secondary)">
    No notifications.
  </div>

  <div *ngFor="let notif of notifications" 
       [style.background]="notif.read ? 'var(--card-bg)' : '#E8F5E9'"
       class="card"
       style="display: flex; gap: 15px; align-items: start; padding: 15px; cursor: pointer; transition: 0.2s"
       (click)="markAsRead(notif._id, notif.read)">
    
    <div style="font-size: 24px; padding-top: 2px;">
      <span *ngIf="notif.type === 'new_message'">💬</span>
      <span *ngIf="notif.type === 'connection_request' || notif.type === 'connection_accepted'">🤝</span>
      <span *ngIf="notif.type === 'job_application' || notif.type === 'application_status'">💼</span>
    </div>
    
    <div style="flex: 1">
      <div style="display: flex; justify-content: space-between; margin-bottom: 5px;">
        <strong style="color: var(--text-primary)">{{ notif.fromUser?.name || 'System' }}</strong>
        <small style="color: var(--text-secondary)">{{ notif.createdAt | date:'shortTime' }}</small>
      </div>
      <p style="margin: 0; color: var(--text-secondary)">{{ notif.message }}</p>
    </div>
    
    <div *ngIf="!notif.read" style="width: 10px; height: 10px; border-radius: 50%; background: var(--success); margin-top: 8px;"></div>
  </div>
</div>

// react-app/src/pages/Notifications.jsx
import React, { useState, useEffect } from 'react';
import axios from 'axios';
import useAuth from '../hooks/useAuth';

const typeIcon = (type) => {
  if (type === 'new_message') return '💬';
  if (type === 'connection_request' || type === 'connection_accepted') return '🤝';
  if (type === 'job_application' || type === 'application_status') return '💼';
  return '🔔';
};

const Notifications = () => {
  const { token } = useAuth();
  const [notifications, setNotifications] = useState([]);
  const [unreadCount, setUnreadCount] = useState(0);

  const fetchNotifications = async () => {
    try {
      const res = await axios.get('http://localhost:5000/api/notify', {
        headers: { Authorization: `Bearer ${token}` }
      });
      setNotifications(res.data);
      const unread = res.data.filter(n => !n.read).length;
      setUnreadCount(unread);
    } catch (err) {
      console.error(err);
    }
  };

  useEffect(() => {
    fetchNotifications();
  }, []);

  const markAllRead = async () => {
    try {
      await axios.put('http://localhost:5000/api/notify/read-all', {}, {
        headers: { Authorization: `Bearer ${token}` }
      });
      fetchNotifications();
    } catch (err) {
      console.error(err);
    }
  };

  const markAsRead = async (id, alreadyRead) => {
    if (alreadyRead) return;
    try {
      await axios.put(`http://localhost:5000/api/notify/${id}/read`, {}, {
        headers: { Authorization: `Bearer ${token}` }
      });
      fetchNotifications();
    } catch (err) {
      console.error(err);
    }
  };

  return (
    <div>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px' }}>
        <h2 style={{ margin: 0 }}>Notifications</h2>
        {unreadCount > 0 && (
          <button className="btn-primary" onClick={markAllRead}>
            Mark All Read ({unreadCount})
          </button>
        )}
      </div>

      {notifications.length === 0 ? (
        <p style={{ color: 'var(--text-secondary)' }}>No notifications.</p>
      ) : (
        notifications.map(notif => (
          <div
            key={notif._id}
            className="card"
            onClick={() => markAsRead(notif._id, notif.read)}
            style={{
              display: 'flex',
              gap: '15px',
              alignItems: 'flex-start',
              padding: '15px',
              cursor: notif.read ? 'default' : 'pointer',
              background: notif.read ? 'var(--card-bg, white)' : '#e8f5e9',
              marginBottom: '10px',
              transition: 'background 0.2s'
            }}
          >
            <div style={{ fontSize: '24px', paddingTop: '2px' }}>
              {typeIcon(notif.type)}
            </div>
            <div style={{ flex: 1 }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: '5px' }}>
                <strong>{notif.fromUser?.name || 'System'}</strong>
                <small style={{ color: 'var(--text-secondary)' }}>
                  {new Date(notif.createdAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                </small>
              </div>
              <p style={{ margin: 0, color: 'var(--text-secondary)' }}>{notif.message}</p>
            </div>
            {!notif.read && (
              <div style={{ width: '10px', height: '10px', borderRadius: '50%', background: 'var(--success, #4caf50)', marginTop: '8px', flexShrink: 0 }} />
            )}
          </div>
        ))
      )}
    </div>
  );
};

export default Notifications;
